/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useMemo, useRef } from "react";
import { useGLTF, Text, useTexture} from "@react-three/drei";
import { Mesh, MeshStandardMaterial, BoxGeometry } from 'three';
import { Vector3 } from '@react-three/fiber';
import { useControls } from "leva";

const cardMaterial = new MeshStandardMaterial({
  color: 'black',
  roughness: 0.3
});

const textMaterial = new MeshStandardMaterial({
  color: "white",
  roughness: 0.3,
});


const CardFront = ({
  position,
  cardScale,
  isPlayer,
  name,
}: {
  position: Vector3
  cardScale: Vector3,
  isPlayer: boolean,
  name: string,
}) => {
  const { fontsize, positionX } = useControls('Card Front', { fontsize: 0.1, positionX: 1 });

  const texture = useTexture('/src/assets/images/single_rune.png');
  texture.repeat.set(1.5,1.5);
  texture.center.set(0,0.3);

  const { nodes } = useGLTF("/src/assets/objects/card-straight-front.glb");
  const imageMaterial = new MeshStandardMaterial({
    map: texture,
    roughness: 0.3,
  });

  return (
    <Suspense fallback={null}>
      <group position={position}>
        <group
          position={[0, 0, 0]}
          rotation={[0, isPlayer ? 0 : Math.PI, 0]}
          scale={cardScale}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube002 as Mesh).geometry}
            material={cardMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube002_1 as Mesh).geometry}
            material={imageMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.Cube002_2 as Mesh).geometry}
            material={cardMaterial}
          />
          <Text
            font={"/src/assets/fonts/PTSansNarrow-Bold.ttf"}
            fontSize={0.25}
            anchorX={"center"}
            position={[-1.4, 0.001, 0]}
            anchorY={"top"}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            material={textMaterial}
          >
            {name}
          </Text>
        </group>
      </group>
    </Suspense>
  );
}

export default CardFront;

useGLTF.preload("/src/assets/objects/card-straight-front.glb");
useTexture.preload("/src/assets/images/single_rune.png");
